name: OfficeNet
description: Test
area_type: MNS
networks:
- name: USOMNS1-P
  vlan: null
  topology: Ring
  tier: I/O and Distributed Controllers
  address_type: RegulBus Crate Address
  address: null
  gateway: null
- name: USOMNS1-S
  vlan: null
  topology: Ring
  tier: I/O and Distributed Controllers
  address_type: RegulBus Crate Address
  address: null
  gateway: null
- name: SUMNS1-P
  vlan: null
  topology: Point-to-Point
  tier: Controllers
  address_type: IPv4 Network
  address: 192.168.98.0/24
  gateway: null
- name: SUMNS1-S
  vlan: null
  topology: Point-to-Point
  tier: Controllers
  address_type: IPv4 Network
  address: 192.168.99.0/24
  gateway: null
- name: VUMNS1-P
  vlan:
    id: 1111
    name: MNS1-P
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.201.0/28
  gateway: 192.168.201.3
- name: VUMNS1-S
  vlan:
    id: 2111
    name: MNS1-S
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.201.128/28
  gateway: 192.168.201.131
devices:
- name: PLCMNS-CK-EX-P
  description: PLC Primary (A)
  model: REGUL R500
  role: PLC
  interfaces:
  - name: eth3
    network_id: VLAN10_Network
    routes: []
    address_type: IPv4 Address
    address: 192.168.10.101
    vlan_mode: Access
  - name: eth4
    network_id: VLAN20_Field
    routes: []
    address_type: IPv4 Address
    address: 10.0.0.10
    vlan_mode: Access
- name: HMI-Station
  description: HMI Station
  model: Wonderware InTouch
  role: Workstation
  interfaces:
  - name: eth0
    network_id: VLAN10_Network
    routes: []
    address_type: IPv4 Address
    address: 192.168.10.150
    vlan_mode: Access
software:
- name: Alpha.Server
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 4572
    description: Для приложений Статистика, Конфигуратор, Управляющий
    direction: outbound
    protocol: TCP
  - index: 3388
    description: Предоставление статистики в Alpha.Historian
    direction: outbound
    protocol: TCP
  - index: 4949
    description: Сохранение данных в Alpha.Historian
    direction: outbound
    protocol: TCP
  - index: 4388
    description: Модуль TCP Server - предоставление данных клиентам
    direction: outbound
    protocol: TCP
  - index: 161
    description: Модуль SNMP Manager - опрос агента
    direction: outbound
    protocol: UDP
  - index: 162
    description: Модуль SNMP Manager - trap-уведомления
    direction: outbound
    protocol: UDP
  - index: 6551
    description: Модуль резервирования - порт основного канала для подключения к резервной
      паре
    direction: outbound
    protocol: TCP
  - index: 6552
    description: Модуль резервирования - порт резервного канала для подключения к
      резервной паре
    direction: outbound
    protocol: TCP
  - index: 8080
    description: Модуль OPC UA Client - порт HTTP/HTTPS протокола
    direction: outbound
    protocol: TCP
  - index: 10502
    description: Модуль Modbus TCP Master -опрос подчиненной станцией
    direction: outbound
    protocol: TCP
  - index: 4572
    description: Для приложений Статистика, Конфигуратор, Управляющий
    direction: inbound
    protocol: TCP
  - index: 4388
    description: Модуль TCP Server - подключение клиентов
    direction: inbound
    protocol: TCP
  - index: 6551
    description: Модуль резервирования - порт основного канала для подключения к резервной
      паре
    direction: inbound
    protocol: TCP
  - index: 6552
    description: Модуль резервирования - порт резервного канала для подключения к
      резервной паре
    direction: inbound
    protocol: TCP
  - index: 8080
    description: Модуль OPC UA Client - порт HTTP/HTTPS протокола
    direction: inbound
    protocol: TCP
  - index: 10502
    description: Модуль Modbus TCP Master -опрос подчиненной станцией
    direction: inbound
    protocol: TCP
- name: Alpha.AccessPoint
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 4388
    description: Подключение к Alpha.Server
    direction: outbound
    protocol: TCP
  - index: 4976
    description: Подключение к Alpha.AccessPoint приложений Статистика, Конфигуратор
    direction: inbound
    protocol: TCP
  - index: 4949
    description: Получение исторических данных от Alpha.Historian
    direction: inbound
    protocol: TCP
- name: Alpha.Domain
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 11010
    description: Alpha.Domain.Agent
    direction: outbound
    protocol: TCP
  - index: 11020
    description: Alpha.Net.Agent
    direction: outbound
    protocol: TCP
  - index: 11010
    description: Alpha.Domain.Agent
    direction: inbound
    protocol: TCP
  - index: 11020
    description: Alpha.Net.Agent
    direction: inbound
    protocol: TCP
- name: Alpha.Security
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 389
    description: Конфигуратор, Агент
    direction: outbound
    protocol: TCP
  - index: 389
    description: LDAP-сервер - запросы данных пользователей, их прав, конфигурирование
    direction: inbound
    protocol: TCP
- name: Alpha.DevStudio
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 11010
    description: Alpha.Net.Agent
    direction: outbound
    protocol: TCP
  - index: 161
    description: SNMP Manager
    direction: outbound
    protocol: UDP
- name: Alpha.HMI
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 4388
    description: Оперативные данные Alpha.Server
    direction: outbound
    protocol: TCP
  - index: 4950
    description: Исторические данные Alpha.Historian
    direction: outbound
    protocol: TCP
- name: Alpha.Historian
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 3388
    description: Подключение приложения Статистика
    direction: inbound
    protocol: TCP
  - index: 4949
    description: Сохранение данных
    direction: inbound
    protocol: TCP
- name: Alpha.Licensing
  description: Alpha.Server
  version: v1.0
  ports:
  - index: 15150
    description: Подключение для запроса лицензий
    direction: inbound
    protocol: TCP
  - index: 15151
    description: Подключение приложения Статистика
    direction: inbound
    protocol: TCP
