name: Krasnoselki-2
description: Автоматизированная система управления технологическим процессом НПС Красносёлки-2 (СА МНС, СА ПТ, САР). Куйбышевское РУ. Техническое перевооружение.
area_type: MNS, PT, ASME
networks:
- name: USOMNS2-P
  description: Сеть СУ МПСА МНС НПС№2 (Основной канал)
  vlan: null
  topology: Ring
  tier: I/O and Distributed Controllers
  address_type: RegulBus Crate Address
  address:
  gateway:
- name: USOMNS2-S
  description: Сеть СУ МПСА МНС НПС№2 (Резервный канал)
  vlan: null
  topology: Ring
  tier: I/O and Distributed Controllers
  address_type: RegulBus Crate Address
  address:
  gateway:
- name: PLCMNS2-P
  description: Сеть синхронизации ПЛК МПСА МНС НПС№2 (Основной канал)
  vlan: null
  topology: Point-to-Point
  tier: Controllers
  address_type: IPv4 Network
  address: 192.168.98.0/24
  gateway: ""
- name: PLCMNS2-S
  description: Сеть синхронизации ПЛК МПСА МНС НПС№2 (Резервный канал)
  vlan: null
  topology: Point-to-Point
  tier: Controllers
  address_type: IPv4 Network
  address: 192.168.99.0/24
  gateway: ""
- name: VUMNS2-P
  description: Сеть ВУ МПСА МНС НПС№1 (Основной канал)
  vlan:
    id: 1121
    name: MNS2-P
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.202.0/28
  gateway: 192.168.202.3
- name: VUMNS2-S
  description: Сеть ВУ МПСА МНС НПС№1 (Резервный канал)
  vlan:
    id: 2121
    name: MNS2-S
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.202.128/28
  gateway: 192.168.202.131
- name: ARMMNS2-P
  description: Сеть АРМ МПСА МНС НПС№1 (Основной канал)
  vlan:
    id: 1122
    name: ARM2-P
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.202.16/28
  gateway: 192.168.202.18
- name: ARMMNS2-S
  description: Сеть АРМ МПСА МНС НПС№1 (Основной канал)
  vlan:
    id: 2122
    name: ARM2-S
  topology: Star
  tier: SCADA and HMI
  address_type: IPv4 Network
  address: 192.168.202.144/28
  gateway: 192.168.202.146
- name: L3-P
  description: Сеть коммутатора L3 ЛВС МДП (Основной канал)
  vlan: null
  topology: Star
  tier: MES Level
  address_type: IPv4 Network
  address: 172.16.0.0/24
  gateway: 172.16.0.1
- name: L3-S
  description: Сеть коммутатора L3 ЛВС МДП (Резервный канал)
  vlan: null
  topology: Star
  tier: MES Level
  address_type: IPv4 Network
  address: 172.16.1.0/24
  gateway: 172.16.1.1
- name: RT-P
  description: Сеть маршрутизатора ЛВС МДП внутреняя (Основной канал)
  vlan: null
  topology: Star
  tier: MES Level
  address_type: IPv4 Network
  address: 172.16.2.0/24
  gateway: 172.16.2.1
- name: RT-S
  description: Сеть маршрутизатора ЛВС МДП внутреняя (Резервный канал)
  vlan: null
  topology: Star
  tier: MES Level
  address_type: IPv4 Network
  address: 172.16.3.0/24
  gateway: 172.16.3.1
devices:
- name: PLCMNS-CK-KS2-P
  description: PLC Primary (A)
  model: REGUL R500
  area_type: MNS
  role: PLC
  interfaces:
  - name: eth3
    network_id: PLCMNS2-P
    routes: []
    address_type: IPv4 Address
    address: 192.168.98.1
    vlan_mode: Access
    software_id: regul_networking
  - name: eth4
    network_id: PLCMNS2-S
    routes: []
    address_type: IPv4 Address
    address: 192.168.99.1
    vlan_mode: Access
    software_id: regul_networking
  - name: eth5
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.1
    vlan_mode: Access
    software_id: regul_networking
  - name: eth6
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.129
    vlan_mode: Access
    software_id: regul_networking
  software_used:
    - NTP Client
    - Modbus TCP
  firewall_id: regul_firewall
- name: PLCMNS-CK-KS2-S
  description: PLC Secondary (B)
  model: REGUL R500
  role: PLC
  area_type: MNS
  interfaces:
  - name: eth3
    network_id: PLCMNS2-P
    routes: []
    address_type: IPv4 Address
    address: 192.168.98.2
    vlan_mode: Access
    software_id: regul_networking
  - name: eth4
    network_id: PLCMNS2-S
    routes: []
    address_type: IPv4 Address
    address: 192.168.99.2
    vlan_mode: Access
    software_id: regul_networking
  - name: eth5
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.2
    vlan_mode: Access
    software_id: regul_networking
  - name: eth6
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.130
    vlan_mode: Access
    software_id: regul_networking
  software_used:
    - NTP Client
    - Modbus TCP
  firewall_id: regul_firewall
- name: AMNS-CK-KS2-S
  description: АРМ Оператора "Красноселки-2" (Резервное)
  model: IROBO
  role: Workstation
  area_type: MNS
  interfaces:
  - name: eth4
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.4
    vlan_mode: Access
    software_id: networking
  - name: eth0
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.132
    vlan_mode: Access
    software_id: networking
  software_used:
      - Alpha.Server
      - Alpha.Domain
      - Alpha.Security
      - Alpha.DevStudio
      - Alpha.HMI
      - Alpha.Historian
      - Alpha.Licensing
      - Alpha.Net
      - NTP Client
      - KLAgent
      - SSH
  firewall_id: iptables
- name: AMNS-SR-KS2-P
  description: АРМ Оператора "Красноселки-2" (Основное)
  model: IROBO
  role: Workstation
  area_type: MNS
  interfaces:
  - name: eth4
    network_id: ARMMNS2-P
    routes:
      - VUMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.17
    vlan_mode: Access
    software_id: networking
  - name: eth0
    network_id: ARMMNS2-S
    routes:
      - VUMNS2-S
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.145
    vlan_mode: Access
    software_id: networking
  software_used:
    - Alpha.Server
    - Alpha.Domain
    - Alpha.Security
    - Alpha.DevStudio
    - Alpha.HMI
    - Alpha.Historian
    - Alpha.Net
    - Alpha.Licensing
    - NTP Client
    - KLAgent
    - SSH
  firewall_id: iptables
- name: NTP-SR-KS2
  description: Сервер точного времени
  model: Virtual
  role: Timeserver
  area_type: MNS, PT, ASME
  interfaces:
  - name: eth0
    network_id: L3-P
    routes:
      - VUMNS2-P
      - ARMMNS2-P
      - RT-P
    address_type: IPv4 Address
    address: 172.16.0.6
    vlan_mode: Access
    software_id: networking
  - name: eth1
    network_id: L3-S
    routes:
      - VUMNS2-S
      - ARMMNS2-S
      - RT-S
    address_type: IPv4 Address
    address: 172.16.1.6
    vlan_mode: Access
    software_id: networking
  software_used:
    - NTP Server
    - SNMP
- name: PPCMNS-SAR-KS2
  description: Дисплейная панель САР "Красноселки-2"
  model: IROBO
  role: Panel
  area_type: MNS
  interfaces:
  - name: eth0
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.11
    vlan_mode: Access
    software_id: networking
  - name: eth1
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.139
    vlan_mode: Access
    software_id: networking
  software_used:
    - Alpha.Server
    - Alpha.Domain
    - Alpha.Security
    - Alpha.DevStudio
    - Alpha.HMI
    - Alpha.Historian
    - Alpha.Licensing
    - Alpha.Net
    - NTP Client
    - KLAgent
    - SSH
  firewall_id: iptables
- name: SWMNS-CK-KS2-P
  description: Коммутатор ВУ МНС НПС №1 "Красноселки-2" (Основной)
  model: Moxa
  role: Switch
  area_type: MNS
  interfaces:
  - name: main
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.9
    vlan_mode: Access
    software_id: moxa_networking
  software_used:
    - NTP Client
    - SNMP
    - SSH
  firewall_id: moxa_firewall
- name: SWMNS-CK-KS2-S
  description: Коммутатор ВУ МНС НПС №1 "Красноселки-2" (Резервный)
  model: Moxa
  role: Switch
  area_type: MNS
  interfaces:
  - name: main
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.137
    vlan_mode: Access
    software_id: moxa_networking
  software_used:
    - NTP Client
    - SNMP
    - SSH
  firewall_id: moxa_firewall
- name: SWMNS-SAR-KS2-P
  description: Коммутатор ВУ САР НПС №1 "Красноселки-2" (Основной)
  model: Moxa
  role: Switch
  area_type: MNS
  interfaces:
  - name: main
    network_id: VUMNS2-P
    routes:
      - ARMMNS2-P
      - L3-P
      - RT-P
    address_type: IPv4 Address
    address: 192.168.202.10
    vlan_mode: Access
    software_id: moxa_networking
  software_used:
    - NTP Client
    - SNMP
    - SSH
  firewall_id: moxa_firewall
- name: SWMNS-SAR-KS2-S
  description: Коммутатор ВУ САР НПС №1 "Красноселки-2" (Резервный)
  model: Moxa
  role: Switch
  area_type: MNS
  interfaces:
  - name: main
    network_id: VUMNS2-S
    routes:
      - ARMMNS2-S
      - L3-S
      - RT-S
    address_type: IPv4 Address
    address: 192.168.202.138
    vlan_mode: Access
    software_id: moxa_networking
  software_used:
    - NTP Client
    - SNMP
    - SSH
  firewall_id: moxa_firewall
software:
- name: Alpha.Net
  description: Сеть Alpha.Net используется для передачи конфигураций, команд и других данных между компьютерами домена
  version: 1.4.12
  ports:
  - index: 11111
    description: Адрес первого агента
    direction: both
    protocol: TCP
  - index: 11112
    description: Адрес второго агента
    direction: both
    protocol: TCP
  - index: 11113
    description: Адрес третьего агента
    direction: both
    protocol: TCP
  - index: 11114
    description: Адрес четвертого агента
    direction: both
    protocol: TCP
  - index: 11115
    description: Адрес пятого агента
    direction: both
    protocol: TCP
- name: Alpha.Server
  description: "Основной сервер платформы Альфа"
  version: "6.4.12+b2.r123509"
  ports:
    - index: 4572
      description: "Подключение к Alpha.Server приложений Статистика, Конфигуратор, Управляющий"
      direction: both
      protocol: TCP
    - index: 4388
      description: "Модуль TCP Server - подключение клиентов / предоставление данных клиентам"
      direction: both
      protocol: TCP
    - index: 6551
      description: "Модуль резервирования - порт основного канала"
      direction: both
      protocol: TCP
    - index: 6552
      description: "Модуль резервирования - порт резервного канала"
      direction: both
      protocol: TCP
    - index: 10502
      description: "Модуль Modbus TCP Slave/Master - подключение опросчика/опрос подчиненной станцией"
      direction: outbound
      protocol: TCP
    - index: 3388
      description: "Предоставление статистики в Alpha.Historian / Подключение приложения Статистика"
      direction: both
      protocol: TCP
    - index: 4949
      description: "Сохранение данных в Alpha.Historian / Получение исторических данных"
      direction: both
      protocol: TCP
    - index: 161
      description: "Модуль SNMP Manager - опрос агента / Контроль целостности"
      direction: both
      protocol: UDP
    - index: 162
      description: "Модуль SNMP Manager - trap-уведомления"
      direction: both
      protocol: UDP
    # - index: 6514
    #   description: "Модуль Syslog Server - получение данных по TLS"
    #   direction: inbound
    #   protocol: TCP
    # - index: 514
    #   description: "Модуль Syslog Server - получение данных по UDP"
    #   direction: inbound
    #   protocol: UDP
    # - index: 8080
    #   description: "Модуль OPC UA - получение/отправка данных по протоколу HTTP/HTTPS"
    #   direction: both
    #   protocol: TCP
    # - index: 62544
    #   description: "Модуль OPC UA - получение/отправка данных по протоколу OPC.TCP"
    #   direction: both
    #   protocol: TCP
    # - index: 2404
    #   description: "Модуль IEC Slave/Master - подключение опросчика/опрос подчиненной станцией"
    #   direction: both
    #   protocol: TCP
    # - index: 102
    #   description: "Модуль IEC-61850 Client - опрос устройств"
    #   direction: outbound
    #   protocol: TCP
    # - index: 9600
    #   description: "Модуль FINS Client - опрос устройств"
    #   direction: outbound
    #   protocol: UDP
- name: Alpha.AccessPoint
  description: "Точка доступа для подключения внешних приложений"
  version: "1.0.0"
  ports:
    - index: 4976
      description: "Подключение к Alpha.AccessPoint приложений Статистика, Конфигуратор"
      direction: both
      protocol: TCP
    - index: 4949
      description: "Получение исторических данных от Alpha.Historian / Сохранение данных"
      direction: both
      protocol: TCP
- name: Alpha.Historian
  description: "Хранилище исторических данных"
  version: "4.0.2+b1.r123650"
  ports:
    - index: 3388
      description: "Предоставление статистики в Alpha.Historian / Подключение приложения Статистика"
      direction: both
      protocol: TCP
    - index: 4949
      description: "Сохранение данных / Получение исторических данных"
      direction: both
      protocol: TCP
- name: Alpha.Domain
  description: "Доменный компонент платформы"
  version: "1.4.12+b1.r120735.x86_64"
  ports:
    - index: 11020
      description: "Alpha.Net.Agent"
      direction: both
      protocol: TCP
    - index: 11010
      description: "Alpha.Domain.Agent"
      direction: both
      protocol: TCP
- name: Alpha.Security
  description: "Компонент безопасности и управления доступом"
  version: "1.7.23+b18.r123496.x86_64"
  ports:
    - index: 389
      description: "LDAP-сервер - запросы данных пользователей, их прав, конфигурирование"
      direction: both
      protocol: TCP
- name: Alpha.Licensing
  description: "Сервис лицензирования"
  version: "1.13.1+b1.r126172.x86_64"
  ports:
    - index: 15150
      description: "Подключение для запроса лицензий"
      direction: both
      protocol: TCP
    - index: 15151
      description: "Подключение приложения Статистика"
      direction: both
      protocol: TCP
- name: Alpha.DevStudio
  description: "Среда разработки"
  version: "3.28.4+b2.r121962"
  ports:
    - index: 11010
      description: "Alpha.Net.Agent / Alpha.Domain.Agent"
      direction: both
      protocol: TCP
- name: Alpha.HMI
  description: "Дизайнер интерфейсов HMI"
  version: "2.0.26+b15.r123251.x86_64"
  ports:
    - index: 4388
      description: "Оперативные данные Alpha.Server / Подключение к Alpha.Server"
      direction: both
      protocol: TCP
    - index: 4950
      description: "Исторические данные Alpha.Historian"
      direction: both
      protocol: TCP
- name: networking
  description: Raise network interfaces
  version: v1.134
- name: regul_networking
  description: Implementation of network in REGUL
  version: v1.0
- name: Modbus TCP
  description: Modbus TCP
  version:
  ports:
  - index: 10502
    description: Modbus TCP
    direction: inbound
    protocol: TCP
- name: NTP Client
  description: Протокол синхронизации времени
  version: v1.0
  ports:
  - index: 123
    description: NTP
    direction: outbound
    protocol: UDP
- name: NTP Server
  description: Протокол синхронизации времени
  version: v1.0
  ports:
  - index: 123
    description: NTP
    direction: inbound
    protocol: UDP
- name: SNMP
  description: Протокол простого управления сетями
  version: v1.0
  ports:
  - index: 161
    description: Данные
    direction: inbound
    protocol: UDP
  - index: 162
    description: Ловушки
    direction: inbound
    protocol: UDP
- name: KLAgent
  description: Kaspersky Agent
  version: v1.5
  ports:
  - index: 14000
    description: Данные
    direction: both
    protocol: TCP
  - index: 13000
    description: Ловушки
    direction: both
    protocol: TCP
  - index: 15000
    description: Ловушки
    direction: both
    protocol: TCP
- name: SSH
  description: Secured Socket Shell
  version: v2.0
  ports:
  - index: 22
    description: Данные
    direction: both
    protocol: TCP
- name: moxa_networking
  description: Raise network interfaces for Moxa switches
  version: v1.0
- name: moxa_firewall
  description: Implementation of firewall in Moxa Switches
  version: v1.0
