name: Build and Package DEB on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev ruby ruby-dev build-essential
          sudo gem install --no-document fpm

      - name: Install Flet
        run: pip install flet

      - name: Build app
        run: flet build linux -v

      - name: Package as .deb
        run: |
          mkdir -p package/usr/local/bin
          cp build/linux/* package/usr/local/bin/halter
          ARCH=$(dpkg --print-architecture)
          VERSION=${GITHUB_REF_NAME#v}
          fpm -s dir -t deb -n halter -v "$VERSION" -a "$ARCH" -C package .

      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: halter-deb
          path: ./*.deb

  release:
    needs: [build-linux]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Download DEB artifact
        uses: actions/download-artifact@v4
        with:
          name: halter-deb
          path: ./release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ./release/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
