name: Build on Tag

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'   # например, теги вида v1.0, v2.3.4 и т.д.

permissions:
  contents: write

jobs:
  build-linux:
      runs-on: ubuntu-latest
      needs: test
      if: success()
      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"
            cache: "pip"
        
        - name: Install GTk-libs
          run: sudo apt-get update &&
              sudo apt-get install -y libgtk-3-dev

        - name: Install Flet
          run: pip install flet

        - name: Build app
          run: flet build linux -v

        - name: Upload Linux artifact
          uses: actions/upload-artifact@v4
          with:
            name: halter-linux
            path: dist/linux/**

  release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: halter-linux
          path: ./halter-linux

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            ./halter-linux/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
